import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.awt.Color;
import javax.swing.SwingConstants;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author PC
 */
public class frmToDo extends javax.swing.JFrame {

CardLayout cardLayout;
    /**
     * Creates new form frmToDo
     */
    public frmToDo() {
    	setTitle("Login");
        initComponents();
        setLocationRelativeTo(null);
        
      
    }
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginPanel = new javax.swing.JPanel();
        lblToDoList = new javax.swing.JLabel();
        lblAdminPanel = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUsername.setHorizontalAlignment(SwingConstants.LEFT);
        tfUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlSignUp = new javax.swing.JPanel();
        btnGoBack = new javax.swing.JButton();
        lblUsername1 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfUserName1 = new javax.swing.JTextField();
        pfPassword1 = new javax.swing.JPasswordField();
        btnSignup1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblsignup = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setMinimumSize(new java.awt.Dimension(1102, 750));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginPanel.setForeground(new java.awt.Color(102, 0, 102));
        pnlLoginPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlLoginPanel.setMinimumSize(new java.awt.Dimension(1102, 750));
        pnlLoginPanel.setPreferredSize(new java.awt.Dimension(1102, 750));
        pnlLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblToDoList.setBackground(new java.awt.Color(255, 255, 255));
        lblToDoList.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        lblToDoList.setText("To Do List");
        pnlLoginPanel.add(lblToDoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 330, 60));

        lblAdminPanel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblAdminPanel.setText("Login Panel");
        pnlLoginPanel.add(lblAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 140, -1));

        lblUsername.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblUsername.setText("Username:");
        pnlLoginPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 300, 100, 40));

        tfUserName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tfUserName.setToolTipText("Enter Username");
        tfUserName.setSelectionColor(new java.awt.Color(153, 102, 0));
        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });
        pnlLoginPanel.add(tfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 190, 40));

        lblPassword.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblPassword.setText("Password:");
        pnlLoginPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 420, 100, 40));

        pfPassword.setFont(new java.awt.Font("Trebuchet MS", 2, 11)); // NOI18N
        pfPassword.setSelectionColor(new java.awt.Color(153, 102, 0));
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        pnlLoginPanel.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 190, 40));

        btnSignUp.setBackground(Color.ORANGE);
        btnSignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSignUp.setIcon(new ImageIcon(this.getClass().getResource("icons8-sign-up-48.png"))); // NOI18N
        btnSignUp.setText("Sign up");
        btnSignUp.setBorderPainted(false);
        btnSignUp.setFocusPainted(false);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        pnlLoginPanel.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 180, 80));

        btnSignIn.setBackground(Color.ORANGE);
        btnSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSignIn.setIcon(new ImageIcon(this.getClass().getResource("icons8-enter-48.png"))); // NOI18N
        btnSignIn.setText("Log in");
        btnSignIn.setBorderPainted(false);
        btnSignIn.setFocusPainted(false);
        btnSignIn.setMaximumSize(new java.awt.Dimension(149, 59));
        btnSignIn.setMinimumSize(new java.awt.Dimension(149, 59));
        btnSignIn.setPreferredSize(new java.awt.Dimension(149, 59));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnSignInActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        pnlLoginPanel.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 180, 80));

        jLabel1.setIcon(new ImageIcon(this.getClass().getResource("icons8-name-48.png"))); // NOI18N
        pnlLoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, 40));

        jLabel3.setIcon(new ImageIcon(this.getClass().getResource("icons8-password-48.png"))); // NOI18N
        pnlLoginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 50, 50));

        lblErrorMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlLoginPanel.add(lblErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 720, 320, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 178));
        jLabel2.setIcon(new ImageIcon(this.getClass().getResource("pexels-olia-danilevich-5088008 (1).jpg"))); // NOI18N
        pnlLoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 750));

        getContentPane().add(pnlLoginPanel, "card2");

        pnlSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoBack.setBackground(Color.ORANGE);
        btnGoBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGoBack.setIcon(new ImageIcon(this.getClass().getResource("icons8-go-back-48.png"))); // NOI18N
        btnGoBack.setText("Go Back");
        btnGoBack.setBorderPainted(false);
        btnGoBack.setFocusable(false);
        btnGoBack.setMaximumSize(new java.awt.Dimension(146, 56));
        btnGoBack.setMinimumSize(new java.awt.Dimension(146, 56));
        btnGoBack.setPreferredSize(new java.awt.Dimension(146, 56));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        pnlSignUp.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 80));

        lblUsername1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblUsername1.setText("Username:");
        pnlSignUp.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 40));

        lblPassword1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblPassword1.setText("Password:");
        pnlSignUp.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 100, 40));

        jLabel4.setIcon(new ImageIcon(this.getClass().getResource("icons8-name-48.png"))); // NOI18N
        pnlSignUp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, 40));

        jLabel5.setIcon(new ImageIcon(this.getClass().getResource("icons8-password-48.png"))); // NOI18N
        pnlSignUp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 50, 50));

        tfUserName1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tfUserName1.setToolTipText("Enter Username");
        tfUserName1.setSelectionColor(new java.awt.Color(153, 102, 0));
        tfUserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserName1ActionPerformed(evt);
            }
        });
        pnlSignUp.add(tfUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 240, 40));

        pfPassword1.setFont(new java.awt.Font("Trebuchet MS", 2, 11)); // NOI18N
        pfPassword1.setSelectionColor(new java.awt.Color(153, 102, 0));
        pfPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassword1ActionPerformed(evt);
            }
        });
        pnlSignUp.add(pfPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 240, 40));

        btnSignup1.setBackground(Color.ORANGE);
        btnSignup1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSignup1.setIcon(new ImageIcon(this.getClass().getResource("icons8-sign-up-48.png"))); // NOI18N
        btnSignup1.setText("Sign up");
        btnSignup1.setBorderPainted(false);
        btnSignup1.setFocusable(false);
        btnSignup1.setMaximumSize(new java.awt.Dimension(146, 56));
        btnSignup1.setMinimumSize(new java.awt.Dimension(146, 56));
        btnSignup1.setPreferredSize(new java.awt.Dimension(146, 56));
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });
        pnlSignUp.add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 170, 80));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel7.setText("Sign up");
        pnlSignUp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        lblsignup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlSignUp.add(lblsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 714, 250, 20));

        jLabel6.setIcon(new ImageIcon(this.getClass().getResource("wooden-board-empty-table-front-blurred-background-perspective-brown-wood-table-blur-trees-forest-background-can-be-used-mock-up-display-montage-your-products-autumn-season (3).jpg"))); // NOI18N
        pnlSignUp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 750));

        getContentPane().add(pnlSignUp, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public int getRowNumberOfAdmins(){
     DBHelper dbHelper = new DBHelper();
     Connection connection;
     PreparedStatement statement;
   int numberRow = 0;
   ResultSet resultSet;
  

try{
    connection= dbHelper.getConnection();
    String query = "select count(*) from admins";
    statement = connection.prepareStatement(query);
    resultSet = statement.executeQuery();
    while(resultSet.next()){
        numberRow = resultSet.getInt("count(*)");
    }
    
}catch (Exception ex){
    System.out.println(ex.getMessage());
}
return numberRow;
}


 


    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_btnSignInActionPerformed
       Connection connection=null;
        DBHelper dbHelper = new DBHelper();
        Statement statement=null;
        ResultSet resultSet;
       
        
        try{
            connection = dbHelper.getConnection();
            statement = connection.createStatement();
            resultSet= statement.executeQuery("select * from admins");
            
            for(int i=0;i<getRowNumberOfAdmins();i++){
            resultSet.next();
           if(resultSet.getString("AdminName").equals(tfUserName.getText()) && resultSet.getString("AdminPassword").equals(pfPassword.getText())){
     
        this.dispose();
        frmToDoList ftdl = new frmToDoList();
        ftdl.setVisible(true);
        }
            
            
           else{
               lblErrorMessage.setText("Username or Password does not match.");
           }
            }
                        
            
        }
            
        
        catch(SQLException exception){
         
            dbHelper.showErrorMessage(exception);
    
        
    }
        finally{
            try{
            statement.close();
            connection.close();
            }
            catch(NullPointerException exception){
            	JOptionPane.showMessageDialog(this,"There is no internet connection.", "Error",JOptionPane.WARNING_MESSAGE);	
            	
            
        }  
           }
       
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
       pnlLoginPanel.setVisible(false);
        pnlSignUp.setVisible(true);
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserNameActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        pnlSignUp.setVisible(false);
        pnlLoginPanel.setVisible(true);
       
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void tfUserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserName1ActionPerformed

    private void pfPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassword1ActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        if(tfUserName1.getText().equals("") || pfPassword1.getText().equals("")){
            lblsignup.setText("Please enter your informations");
        }
        else{
        
        Connection connection=null;
        DBHelper dbHelper = new DBHelper();
        PreparedStatement statement=null;
        try{
            connection=dbHelper.getConnection();
            String sql = "insert into admins(AdminName,AdminPassword)values(?,?)";
            statement = connection.prepareStatement(sql);
            statement.setString(1,tfUserName1.getText());
            statement.setString(2,pfPassword1.getText());
            
            int result = statement.executeUpdate();
            

        }
        catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
        }
        finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmToDoList.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        lblsignup.setText("Admin account has been successfully created.");
        pnlSignUp.setVisible(false);
        pnlLoginPanel.setVisible(true);
        }
    }//GEN-LAST:event_btnSignup1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new frmToDo().setVisible(true);
                       
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnSignup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAdminPanel;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblToDoList;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblsignup;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPasswordField pfPassword1;
    private javax.swing.JPanel pnlLoginPanel;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JTextField tfUserName;
    private javax.swing.JTextField tfUserName1;
    // End of variables declaration//GEN-END:variables
}